### ISSUE TITLE
Extension can broke excluded files in some case

### ISSUE THREAD

**Issue by PFight** [eamodio/vscode-toggle-excluded-files#6]
Something happened, and my excluded files stop working. I investigated and found reason.

Steps to reproduce:
1) toggle excluded files with extension. All "files.exclude" become "true".
2) edit some rule by hands and make it "false"
3) untoggle excluded files with extension. All rules become "false".
4) toggle again, all rules but rule from step 2 become "true".

Looks like something (crash of vscode or smth) occured between toggle/untogle, and disabled rules stuck  disabled at all, until I edited them by hand. 

I will write more concrete scenario if I will able to reproduce it again.

**Comment by avionbg** [comment]
Happened to me also, modifying by hand all files/folders to true fixed the issue.

**Comment by eamodio** [comment]
Can you please see if this issue is still reproducible in the pre-release edition? Thanks!

You can switch to the pre-release edition, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
